### PR TITLE
OV-314: Change menu body height and position so it does not cover the timeline

### LINKED ISSUE #314: BUG: Script panel overlaps with timeline
### Describe your issue

On the Studio page the Script panel overlaps with the timeline.

### Steps to reproduce

1. Open the site: FEAT: http://bsa-2024-outreachvids-dev.eu-north-1.elasticbeanstalk.com/.
2. Press the 'Create video' button.
3. Select any landscape.
4. In the side menu select 'Script'.
5. Observe the Script panel.

### What was the actual result?

The Script panel overlaps with the timeline.

Image

### What was the expected result?

The Script panel should not overlap with the timeline.

Image

### Put here any screenshots or videos (optional)

Please see above.

### What OS are you seeing the problem on?

Windows 11

### What browsers are you seeing the problem on?

Firefox 129.0.2 (64x)
Chrome 128.0.6613.113 (x64)

### Severity

Minor (S4)

### PR DESCRIPTION
**Pull request by stefano-lacorazza**
Decreased the menu body height and moved it up so it doesn't cover the timeline component.
image

### CODE REVIEW

**Comment by sofiia-trokhymchuk** [comment]
Could you please show how it looks with different screen resolutions?

**Comment by stefano-lacorazza** [comment]
> Could you please show how it looks with different screen resolutions?


https://github.com/user-attachments/assets/32edb2ae-39ed-401a-829d-aac4c0fa6638

**Comment by sofiia-trokhymchuk** [comment]
Have you tried uncommenting sidebar menu items?

**Comment by stefano-lacorazza** [comment]
> Have you tried uncommenting sidebar menu items?

I didnt do it initially but works great still

Uploading OutreachVids - Google Chrome 2024-09-18 05-12-46.mp4…

**Review by anton-otroshchenko — APPROVED** [review]

**Review by sergiy4 — APPROVED** [review]

**Review by sofiia-trokhymchuk — APPROVED** [review]

**Pull request merged**
